### PR TITLE
#234: Scriptoni does not log errors (closes #234)

### LINKED ISSUE #234: Scriptoni does not log errors
## description
The function that calls `process.exit(1);` does not log the corresponding error.

image

## how to reproduce
1. modify something to make a script fail (e.g., cancel the Config file for `web-build`)
2. run the failing script
3. no errors displayed

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by ecamellini**
Closes #234

### tests performed

Tested locally by removing config file for `web-build`:

screenshot 2019-01-03 at 10 57 55

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -53,6 +53,7 @@ function runScript(script: Script): Promise<void> {
   }
 }
 
-runScript(script).catch(() => {
+runScript(script).catch(error => {
+  logger.bin(`${script} script error: ${error}`);
```
Comment (FrancescoCioria) [inline src/index.ts]: does it log it in "red"?
as it's an error I would it to be clearly red in the terminal

Comment (ecamellini) [reply src/index.ts]: True, trying to fix that right now

Comment (ecamellini) [reply src/index.ts]: Ok, now it's red: 
image
