### PR TITLE
#198: doe not work on Windows (closes #198)

### LINKED ISSUE #198: doe not work on Windows
## description
`rm -rf`, `mkdir`, ... => they do not work on Windows!!
also, on windows we don't get any error, the process simply ends :/

## how to reproduce
- run scriptoni dev build on windows

## specs
create/remove files/folders with NodeJS API

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #198

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

File: bin/scriptoni.js [hunk 1]
```diff
@@ -20,13 +22,11 @@ function execSync(command, options) {
...
-/*
- * clean /build folder
- */
+
 function clean() {
-  execSync('rm -rf build/*', execSyncOptions);
-  execSync('mkdir -p build', execSyncOptions);
+  logger.bin('clean /build folder')
+  rimraf.sync('build');
+  fs.mkdirSync('build');
```
Comment (giogonzo) [inline bin/scriptoni.js]: are you sure these `build` paths are still OK? we were passing a `cwd` to exec before, depending on the cwd of the caller of scriptoni.. not sure how `rimraf.sync` and `mkDirSync` behave? probably already ok?
