### PR TITLE
#142: dev server configuration should allow browser history location (closes #142)

### LINKED ISSUE #142: dev server configuration should allow browser history location
## description
currently `/route` is a not found -> not possible to use the history api with scriptoni

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
use https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback in https://github.com/buildo/scriptoni/blob/master/src/scripts/webpack/dev.js

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by giogonzo**
Closes #142

## Test Plan

- tested on alinity pro 👍 

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/scripts/webpack/dev-ts.js [hunk 1]
```diff
@@ -15,7 +15,8 @@ const server = new webpackServer(compiler(getWebpackConfig), {
   contentBase: paths.BUILD,
   hot: true,
   stats: statsOutputConfiguration,
-  disableHostCheck: true
+  disableHostCheck: true,
+  historyApiFallback: { verbose: true }
```
Comment (giogonzo) [inline src/scripts/webpack/dev-ts.js]: verbose so that we can notice weird redirects, if any
