### PR TITLE
#86: cleanup webpack config handling (closes #86)

### LINKED ISSUE #86: cleanup webpack config handling
## description
Two slightly related problems:
- the error given in case of broken `Config.js` is misleading: we should differentiate between config file not found and config file broken
- the default config does not define a `bundle` key, so code crashes if falling back to the default one

## how to reproduce
- run `scriptoni build` with an invalid (e.g. invalid syntax or invalid import) `Config.js` in your project

## specs
in https://github.com/buildo/scriptoni/blob/master/src/scripts/webpack/config.js#L36
- first, `fs.statSync(configTypePath)` and log the current warning if file is actually not there
- then, fail without catching if syntax is not OK in that file (or any other problem.. basically, if `require`ing it fails)

also, before accessing `ConfigType.meta.props.bundle...`
- update the code to check for the existence of `.bundle` in the type (e.g.: the default type doesn't have it)

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by ecamellini**
Closes #86

### tests performed
* tested on a local project that the errors are different when `config/Config.js` does not exist and is broken.
* tested also that the default config works by removing the config folder and running `npm start`

### CODE REVIEW

File: src/scripts/webpack/config.js [hunk 1]
```diff
@@ -34,16 +39,22 @@ const readOptionalConfigFile = fullPath => {
...
     return require(configTypePath);
   } catch (e) {
     /* eslint-disable no-console */
-    console.warn(`
-      No Config type definition file found in ${configTypePath}, using the default one...
-    `);
+    console.error(`Invalid Config type definition file: ${configTypePath}`);
     /* eslint-enable no-console */
-    return t.Any;
+    process.exit(1);
```
Comment (giogonzo) [inline src/scripts/webpack/config.js]: Minor, and I thought about this after our offline discussion, but: "Invalid Config" is a bit misleading, we are not validating the config with respect to a type here (yet). Also in this way we are not reporting the precise error to the user.

Instead, I'd propose to simplify this even further and:
- remove the `try/catch`
- keep the `if (!fs.existsSync)` block as it is now
- just plain `return require(configTypePath)`

In this way, if the file is not valid JS we just fail and report the original error to the user

Comment (ecamellini) [inline src/scripts/webpack/config.js]: 👍
